version: '3'

services:
  mysql-database:
    image: mysql:8
    container_name: mysql-database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:        
      - MYSQL_ROOT_PASSWORD=database-password
      - MYSQL_DATABASE=database-name
    volumes:
      - ./vol/mysql:/var/lib/mysql